---
- name: Run post-install commands
  ansible.builtin.command:
    cmd: "{{ item.command }}"
    creates: "{{ item.creates | default(omit) }}"
  loop: "{{ post_install_commands }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create libxml2.so.2 symlink for Omnissa Horizon Client
  ansible.builtin.file:
    src: libxml2.so.16
    dest: /usr/lib/x86_64-linux-gnu/libxml2.so.2
    state: link
