---
- name: Install standard apt packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: true

- name: Install packages from external repositories
  ansible.builtin.apt:
    name: "{{ external_packages }}"
    state: present
